//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripeAndTwilio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmOrder
    {
        public int Coid { get; set; }
        public Nullable<int> Oid { get; set; }
        public Nullable<int> Sid { get; set; }
        public string Notes { get; set; }
        public string instruction { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> Cid { get; set; }
        public string OStatus { get; set; }
    
        public virtual Orderinfo Orderinfo { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
