//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripeAndTwilio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderinfo()
        {
            this.ConfirmOrders = new HashSet<ConfirmOrder>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Oid { get; set; }
        public Nullable<int> ONumber { get; set; }
        public Nullable<System.DateTime> ODate { get; set; }
        public Nullable<System.DateTime> Pickuptime { get; set; }
        public string Pickupplace { get; set; }
        public string DropOffloc { get; set; }
        public Nullable<int> NetAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmOrder> ConfirmOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
