//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripeAndTwilio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PID { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> Bags { get; set; }
        public Nullable<int> Intialamount { get; set; }
    }
}
